services:
  - type: web
    name: gateway
    env: docker
    dockerfilePath: apps/gateway/Dockerfile
    plan: free

  - type: web
    name: auth
    env: docker
    dockerfilePath: apps/auth/Dockerfile
    plan: free

  - type: web
    name: core
    env: docker
    dockerfilePath: apps/core/Dockerfile
    plan: free
